# Generated by Django 3.2.6 on 2021-08-25 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=150, verbose_name='city')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'Citys',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_code', models.CharField(max_length=5, unique=True, verbose_name='Hotel Code')),
                ('hotel_name', models.CharField(max_length=150, verbose_name='Hotel Name')),
                ('cit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.city')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
    ]
